### ISSUE TITLE
Convert forecast dates to date ranges

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/cfpb-eprocurement#11]
One of our assumptions is that forecasted date ranges are more useful to CORs than made up dates. 
I think it's easier to keep the dates in the fake data as single dates, so I wonder whether we can have Jekyll add a few dates on either end of the "forecasted date" to make it into a range. For example, under the "forecasted date" in the first row, could 01/11/2016 become 01/09/2016-01/12/2016?

**Comment by el-mapache** [comment]
So what you'd like is:

Given the date 01/01/2016, print `12/30/2015 - 01/02/2016`. Two days before and one day following?

**Comment by colinpmacarthur** [comment]
Yep!
