### ISSUE TITLE
"Running" column

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/cfpb-eprocurement#12]
Right now, we have a couple columns in the timeline that look like this:

![screen shot 2016-07-05 at 12 04 20 pm](https://cloud.githubusercontent.com/assets/2092076/16591172/a2235d32-42a8-11e6-91ca-c58b8c97c93a.png)

The "running" column shows the cumulative delay to the project. So, the delays on previous milestones add up to contribute to this "running" delay.

I'm worried this wording won't make sense to users. @kategarklavs: Can you help us out?

**Comment by kategarklavs** [comment]
@colinpmacarthur Hey! Happy to help out. I'd recommend replacing _Running_ with _Total_ or _To date_. One question, though: If the _Running_ column displays the cumulative delay, does the _Days_ column display only the delay for a certain phase? (If that's the case, renaming _Days_ to _Phase_ or _Stage_ might also help contextualize both column titles.)

**Comment by colinpmacarthur** [comment]
Yes, that's exactly right. Thoughts about renaming the "days" column?

**Comment by kategarklavs** [comment]
@colinpmacarthur Sounds good. In that case, I'd recommend replacing _Days_ with _Phase_ (or _Stage_ — whichever is the preferred description). How does that sound?

**Comment by colinpmacarthur** [comment]
Hmm. So, the column header is "Delay" and its two child columns are "Phase" and "Cumulative"? I think that makes sense, although I wonder whether phase will confuse people? And do we need the word days in their somewhere (so they know what unit the delay is in.)

**Comment by kategarklavs** [comment]
An excellent point re: including the word _days_. 

What about this?

Delay (days)

This phase | To date

My hope is that the parenthetical (days) will clarify that days = the unit of measure, but we could also use Delay (in days), if you think that would even further reduce confusion. (Likewise, we could replace _To date_ with _In total_, if users would respond better to the latter option.)

**Comment by colinpmacarthur** [comment]
Sounds good!

So, @el-mapache, can you change the headers of the timeline table to be something like:

Delay (days)
This phase | To date

**Comment by kategarklavs** [comment]
@colinpmacarthur Excellent! And, as I said, I'm happy to iterate on these options if they prove to be confusing to users.
