### ISSUE TITLE
Update data to have more procurements and timelines

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/cfpb-eprocurement#14]
Add timeline data for other procurements to the fake data file.

**Comment by colinpmacarthur** [comment]
I will do.

**Comment by colinpmacarthur** [comment]
OK, new data here: https://docs.google.com/spreadsheets/d/1aHUZGwqN1ymhIxR6PglgQOFfAyFr1YPkdn9CsNKg0JI/edit#gid=1691341553

**Comment by el-mapache** [comment]
PR is merged and the data looks good, closing.
